export const BASE_CHORD_RULES = [
  {"name": "Augmented ", "pitchClass": [0, 4, 8], "quality": "Augmented", "symbol": "aug"},
  {"name": "Augmented eleventh ", "pitchClass": [0, 4, 7, 10, 2, 6], "quality": "Major", "symbol": "aug11"},
  {"name": "Augmented major seventh ", "pitchClass": [0, 4, 8, 11], "quality": "Augmented", "symbol": "augM7"},
  {"name": "Augmented seventh ", "pitchClass": [0, 4, 8, 10], "quality": "Augmented", "symbol": "aug7"},
  {"name": "Augmented sixth ", "pitchClass": [0, 6, 10], "quality": "Predominant", "symbol": "aug6"},
  {"name": "Diminished ", "pitchClass": [0, 3, 6], "quality": "Diminished", "symbol": "dim"},
  {"name": "Diminished major seventh ", "pitchClass": [0, 3, 6, 11], "quality": "Diminished", "symbol": "dimM7"},
  {"name": "Diminished seventh  ", "pitchClass": [0, 3, 6, 9], "quality": "Diminished", "symbol": "dim7"},
  {"name": "Dominant", "pitchClass": [0, 4, 7], "quality": "Major", "symbol": ""},
  {"name": "Dominant eleventh ", "pitchClass": [0, 4, 7, 10, 2, 5], "quality": "Major", "symbol": "11"},
  {"name": "Dominant minor ninth", "pitchClass": [0, 4, 7, 10, 1], "quality": "Major", "symbol": "7b9"},
  {"name": "Dominant ninth", "pitchClass": [0, 4, 7, 10, 2], "quality": "Major", "symbol": "9"},
  {"name": "Added ninth", "pitchClass": [0, 4, 7, 2], "quality": "Major", "symbol": "add9"},
  {"name": "Dominant seventh ", "pitchClass": [0, 4, 7, 10], "quality": "Major", "symbol": "7"},
  {"name": "Dominant seventh flat five ", "pitchClass": [0, 4, 6, 10], "quality": "Diminished", "symbol": "7b5"},
  {"name": "Dominant seventh sharp nine / Hendrix ", "pitchClass": [0, 4, 7, 10, 3], "quality": "Major", "symbol": "7#9"},
  {"name": "Dominant thirteenth ", "pitchClass": [0, 4, 7, 10, 2, 5, 9], "quality": "Major", "symbol": "13"},
  {"name": "Dream ", "pitchClass": [0, 5, 6, 7], "quality": "Just", "symbol": "dream"},
  {"name": "Elektra ", "pitchClass": [0, 7, 9, 1, 4], "quality": "Bitonal", "symbol": "elektra"},
  {"name": "Farben ", "pitchClass": [0, 8, 11, 4, 9], "quality": "Atonal", "symbol": "farben"},
  {"name": "Half-diminished seventh ", "pitchClass": [0, 3, 6, 10], "quality": "Diminished", "symbol": "ø7"},
  {"name": "Lydian ", "pitchClass": [0, 4, 7, 11, 6], "quality": "Major", "symbol": "lydian"},
  {"name": "Magic ", "pitchClass": [0, 1, 5, 6, 10, 0, 3, 5], "quality": "Just", "symbol": "magic"},
  {"name": "Major eleventh ", "pitchClass": [0, 4, 7, 11, 2, 5], "quality": "Major", "symbol": "M11"},
  {"name": "Major seventh ", "pitchClass": [0, 4, 7, 11], "quality": "Major", "symbol": "M7"},
  {"name": "Major seventh sharp eleventh ", "pitchClass": [0, 4, 8, 11, 6], "quality": "Augmented", "symbol": "M7#11"},
  {"name": "Major sixth ", "pitchClass": [0, 4, 7, 9], "quality": "Major", "symbol": "M6"},
  {"name": "Major sixth ninth ", "pitchClass": [0, 4, 7, 9, 2], "quality": "Major", "symbol": "M6add9"},
  {"name": "Major ninth ", "pitchClass": [0, 4, 7, 11, 2], "quality": "Major", "symbol": "M9"},
  {"name": "Major thirteenth ", "pitchClass": [0, 4, 7, 11, 2, 6, 9], "quality": "Major", "symbol": "M13"},
  {"name": "Minor ", "pitchClass": [0, 3, 7], "quality": "Minor", "symbol": "m"},
  {"name": "Minor eleventh ", "pitchClass": [0, 3, 7, 10, 2, 5], "quality": "Minor", "symbol": "m11"},
  {"name": "Minor major seventh ", "pitchClass": [0, 3, 7, 11], "quality": "Minor", "symbol": "mM7"},
  {"name": "Minor ninth ", "pitchClass": [0, 3, 7, 10, 2], "quality": "Minor", "symbol": "m9"},
  {"name": "Minor seventh ", "pitchClass": [0, 3, 7, 10], "quality": "Minor", "symbol": "m7"},
  {"name": "Minor sixth ", "pitchClass": [0, 3, 7, 9], "quality": "Minor", "symbol": "m6"},
  {"name": "Minor sixth ninth  ", "pitchClass": [0, 3, 7, 9, 2], "quality": "Minor", "symbol": "m6add9"},
  {"name": "Minor thirteenth ", "pitchClass": [0, 3, 7, 10, 2, 5, 9], "quality": "Minor", "symbol": "m13"},
  {"name": "Mu ", "pitchClass": [0, 2, 4, 7], "quality": "Major", "symbol": "mu"},
  {"name": "Mystic ", "pitchClass": [0, 6, 10, 4, 9, 2], "quality": "Atonal", "symbol": "mystic"},
  {"name": "Neapolitan ", "pitchClass": [1, 5, 8], "quality": "Major", "symbol": "neapolitan"},
  {"name": "Ninth augmented fifth ", "pitchClass": [0, 4, 8, 10, 2], "quality": "Augmented", "symbol": "9aug5"},
  {"name": "Ninth flat fifth ", "pitchClass": [0, 4, 6, 10, 2], "quality": "M3,+d5,", "symbol": "9b5"},
  {"name": "Northern lights ", "pitchClass": [1, 2, 8, 0, 3, 6, 7, 10, 11, 4, 7], "quality": "Atonal", "symbol": "northern lights"},
  {"name": "Ode-to-Napoleon hexa", "pitchClass": [0, 1, 4, 5, 8, 9], "quality": "Atonal", "symbol": "ode-to-napoleon"},
  {"name": "Petrushka ", "pitchClass": [0, 1, 4, 6, 7, 10], "quality": "Bitonal", "symbol": "petrushka"},
  {"name": "Power ", "pitchClass": [0, 7], "quality": "Indeterminate", "symbol": "P"},
  {"name": "Seven six ", "pitchClass": [0, 4, 7, 9, 10], "quality": "Major", "symbol": "7/6"},
  {"name": "Seventh suspension four ", "pitchClass": [0, 5, 7, 10], "quality": "Suspended", "symbol": "7sus4"},
  {"name": "So What ", "pitchClass": [0, 5, 10, 3, 7], "quality": "Bitonal", "symbol": "so what"},
  {"name": "Suspended Fourth", "pitchClass": [0, 5, 7], "quality": "Suspended", "symbol": "sus4"},
  {"name": "Suspended Second", "pitchClass": [0, 2, 7], "quality": "Suspended", "symbol": "sus2"},
  {"name": "Thirteenth flat ninth ", "pitchClass": [0, 4, 7, 10, 1, 9], "quality": "Major", "symbol": "13b9"},
  {"name": "Thirteenth flat ninth flat fifth ", "pitchClass": [0, 4, 6, 10, 1, 9], "quality": "M3+d5", "symbol": "13b9b5"},
  {"name": "Viennese tri v1", "pitchClass": [0, 1, 6], "quality": "Atonal", "symbol": "vienesse tri1"},
  {"name": "Viennese tri v2", "pitchClass": [0, 6, 7], "quality": "Atonal", "symbol": "vienesse tri2"}
];